### PR TITLE
fix to work with happy >=1.19.10

### PR DESCRIPTION
**Pull request by msakai**
The `HappyWrap` newtypes introduced by https://github.com/simonmar/happy/pull/134 produces code like

```haskell
newtype HappyWrap4 = HappyWrap4 ([TPTP_Input_ c])
```

which results in "Not in scope: type variable" errors.

This commit avoid the problem by using concrete types instead of type variable, though I'm not sure if this is a desired fix.

### CODE REVIEW

**Comment by msakai** [comment]
Friendly ping, @DanielSchuessler.

**Comment by DanielSchuessler** [comment]
@msakai: Sorry for the late response. Since you've been doing most of the work on this package lately, and since I've not been finding enough time to maintain this package properly, should I maybe just add you to the Maintainer Group on Hackage (so you can upload new versions)? You can also become the official Maintainer in the cabal file etc. if you like; otherwise I guess I should set the field to empty :)

**Comment by msakai** [comment]
> should I maybe just add you to the Maintainer Group on Hackage (so you can upload new versions)?

Thanks. I would be more than happy to help with.
My Hackage account is [MasahiroSakai](https://hackage.haskell.org/user/MasahiroSakai).
Also it would be nice if you add me as a collaborator to this repository, so that issues and PRs can be handled in this repository as before.

> You can also become the official Maintainer in the cabal file etc. if you like; otherwise I guess I should set the field to empty :)

I think it is better to have someone's name written in the Maintainer field than being empty.
So I'm okay to be listed as a maintainer.

**Comment by msakai** [comment]
Thanks a lot for making me a collaborator on this repo and a maintainer on Hackage!

**Comment by DanielSchuessler** [comment]
You're welcome :) I got interrupted by something after setting the permissions (like two weeks ago) and then forgot to reply here that I set them already, sorry.
